"""Initial migration with model changes

Revision ID: c3d746db8a07
Revises: 
Create Date: 2025-06-27 11:05:56.589494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c3d746db8a07'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('application_id', sa.String(length=36), nullable=False),
    sa.Column('jd_id', sa.String(length=36), nullable=False),
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.Column('applied_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['jd_id'], ['job_descriptions.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['consultant_profiles.id'], ),
    sa.PrimaryKeyConstraint('application_id'),
    sa.UniqueConstraint('jd_id', 'profile_id', name='uq_application_once_per_jd')
    )
    op.drop_table('emp')
    op.add_column('consultant_profiles', sa.Column('user_id', sa.String(length=36), nullable=False))
    op.alter_column('consultant_profiles', 'experience',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('consultant_profiles', 'content_hash',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.drop_index(op.f('ix_consultant_profiles_id'), table_name='consultant_profiles')
    op.create_unique_constraint(None, 'consultant_profiles', ['email'])
    op.create_foreign_key(None, 'consultant_profiles', 'users', ['user_id'], ['user_id'])
    op.alter_column('job_descriptions', 'user_id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('job_descriptions', 'end_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('((curdate()'))
    op.drop_index(op.f('ix_job_descriptions_id'), table_name='job_descriptions')
    op.drop_constraint(op.f('fk_job_user'), 'job_descriptions', type_='foreignkey')
    op.create_foreign_key(None, 'job_descriptions', 'users', ['user_id'], ['user_id'])
    op.create_unique_constraint('uq_ranking_once_per_jd', 'rankings', ['jd_id', 'profile_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_ranking_once_per_jd', 'rankings', type_='unique')
    op.drop_constraint(None, 'job_descriptions', type_='foreignkey')
    op.create_foreign_key(op.f('fk_job_user'), 'job_descriptions', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.create_index(op.f('ix_job_descriptions_id'), 'job_descriptions', ['id'], unique=False)
    op.alter_column('job_descriptions', 'end_date',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               existing_nullable=False,
               existing_server_default=sa.text('((curdate()'))
    op.alter_column('job_descriptions', 'user_id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)
    op.drop_constraint(None, 'consultant_profiles', type_='foreignkey')
    op.drop_constraint(None, 'consultant_profiles', type_='unique')
    op.create_index(op.f('ix_consultant_profiles_id'), 'consultant_profiles', ['id'], unique=False)
    op.alter_column('consultant_profiles', 'content_hash',
               existing_type=sa.String(length=64),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('consultant_profiles', 'experience',
               existing_type=sa.String(length=64),
               type_=mysql.TEXT(),
               existing_nullable=False)
    op.drop_column('consultant_profiles', 'user_id')
    op.create_table('emp',
    sa.Column('ename', mysql.CHAR(length=1), nullable=True),
    sa.Column('dob', sa.DATE(), nullable=True),
    sa.Column('sal', mysql.INTEGER(), autoincrement=False, nullable=True),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('applications')
    # ### end Alembic commands ###
